## Dashboard Creation and Automated Reporting Instruction Manual

### Required Application Downloads

### Grab and Open Files

In [21]:
#Library Importation
import openpyxl
from openpyxl import load_workbook
import pandas as pd
import numpy as np

#Loading Necessary Workbooks
wb1 = load_workbook ("StaffPerformanceOverviewCR06-23-23 test copy.xlsx")
wb2 = load_workbook("StaffPerformanceOverviewNH06-23-23 test copy.xlsx")
ws1 = wb1.active
ws2 = wb2.active

#Appending Data To One Workbook
for row in ws2.iter_rows(min_row=2, values_only=True): 
    ws1.append(row)

wb1.save("StaffPerformanceOverviewtest-06-23 test copy.xlsx")

#reload new workbook that was just saved
wb = load_workbook("StaffPerformanceOverviewtest-06-23 test copy.xlsx")
ws = wb.active

#Remove Row to consolidate data
start_row = 12
num_rows_to_remove = 1
ws.delete_rows(start_row, num_rows_to_remove)

# Define the column letter you want to update (e.g., column A)
column_letter = 'E'

# Define the value to be replaced and its corresponding replacement
old = "NA"
new = "0"

# Get the column index from the column letter
column_index = ord(column_letter) - ord('A') + 1

# Loop through the cells in the selected column and replace the old value with the new value
for row in ws.iter_rows(min_row=3, min_col=column_index, max_col=column_index):
    cell = row[0]
    if cell.value == old:
        cell.value = new

from openpyxl.styles import NamedStyle

# Create named style for the whole number format
whole_number_style = NamedStyle(name="whole_number", number_format="0")

# Columns that need to be formatted as a whole number (example: columns A, B, and D)
columns_to_format = ['B', 'C', 'D']  # Replace with the letters of the columns you want to format

# Apply the named style to each cell in the selected columns
for column_letter in columns_to_format:
    for cell in ws[column_letter]:
        cell.style = whole_number_style

Decimal_Number_Style = NamedStyle(name="decimal", number_format="#,##0.00")

column_letter = 'E'
for cell in ws[column_letter]:
    cell.style = Decimal_Number_Style

# Create named style for the whole number format
currency_style = NamedStyle(name="currency", number_format='"$"#,##0.00')

# Columns that need to be formatted as a whole number (example: columns A, B, and D)
columns_to_format = ['F', 'G', 'H','I','J','K','L','M','N','O']  # Replace with the letters of the columns you want to format

# Apply the named style to each cell in the selected columns
for column_letter in columns_to_format:
    for cell in ws[column_letter]:
        cell.style = currency_style

wb.save("StaffPerformanceOverviewtest-06-23 test copy.xlsx")

***

In [22]:
import pandas as pd
from openpyxl import load_workbook

# Load the existing Excel workbook
wb = load_workbook("StaffPerformanceOverviewtest-06-23 test copy.xlsx")

# Select the worksheet you want to update (assuming it's the first sheet)
ws = wb.active

# Read the data from the worksheet into a Pandas DataFrame
data_range_location1 = ws['A3:D10']  # Assuming data for location 1 is in column A starting from row 2
data_location1 = [[cell.value for cell in row] for row in data_range_location1]

data_range_location2 = ws['A11:D18']  # Assuming data for location 2 is in column E starting from row 2
data_location2 = [[cell.value for cell in row] for row in data_range_location2]

# Create separate DataFrames for location 1 and location 2
df_location1 = pd.DataFrame(data_location1, columns=['EmployeeID', 'Data1', 'Data2', 'Data3'])
df_location2 = pd.DataFrame(data_location2, columns=['EmployeeID', 'Data1', 'Data2', 'Data3'])

# Consolidate data based on EmployeeID and sum the values for each location
consolidated_data_location1 = df_location1.groupby('EmployeeID', as_index=False).sum()
consolidated_data_location2 = df_location2.groupby('EmployeeID', as_index=False).sum()

# Merge the consolidated data for employees working at both locations (inner merge)
consolidated_data_both_locations = pd.merge(consolidated_data_location1, consolidated_data_location2, on='EmployeeID', suffixes=('_loc1', '_loc2'), how='inner')
consolidated_data_both_locations['Data1'] = consolidated_data_both_locations['Data1_loc1'] + consolidated_data_both_locations['Data1_loc2']
consolidated_data_both_locations['Data2'] = consolidated_data_both_locations['Data2_loc1'] + consolidated_data_both_locations['Data2_loc2']
consolidated_data_both_locations['Data3'] = consolidated_data_both_locations['Data3_loc1'] + consolidated_data_both_locations['Data3_loc2']

# Remove the unnecessary columns from the consolidated DataFrame
consolidated_data_both_locations.drop(columns=['Data1_loc1', 'Data1_loc2', 'Data2_loc1', 'Data2_loc2', 'Data3_loc1', 'Data3_loc2'], inplace=True)

# Convert the consolidated data to a list
consolidated_data_list = consolidated_data_both_locations.values.tolist()

# Determine the starting row for placing the consolidated data
start_row = 3  # Assuming you want to start placing the consolidated data in row 2

# Put the consolidated data back into the Excel worksheet
for row_index, row_data in enumerate(consolidated_data_list):
    for col_index, cell_value in enumerate(row_data):
        cell = ws.cell(row=start_row + row_index, column=col_index + 1)
        cell.value = cell_value

# Save the updated workbook
wb.save("StaffPerformanceOverviewtest-06-23 test copy.xlsx")


***

In [19]:
import pandas as pd
from openpyxl import load_workbook

# Load the existing Excel workbook
wb = load_workbook("StaffPerformanceOverviewtest-06-23 test copy.xlsx")

# Select the worksheet you want to update (assuming it's the first sheet)
ws = wb.active

# Read the data from the worksheet into a Pandas DataFrame
data_range_location1 = ws['A3:D10']  # Assuming data for location 1 is in column A starting from row 2
data_location1 = [[cell.value for cell in row] for row in data_range_location1]

data_range_location2 = ws['A11:D18']  # Assuming data for location 2 is in column E starting from row 2
data_location2 = [[cell.value for cell in row] for row in data_range_location2]

# Create separate DataFrames for location 1 and location 2
df_location1 = pd.DataFrame(data_location1, columns=['EmployeeID', 'Data1', 'Data2', 'Data3'])
df_location2 = pd.DataFrame(data_location2, columns=['EmployeeID', 'Data1', 'Data2', 'Data3'])

# Consolidate data based on EmployeeID and sum the values for each location
consolidated_data_location1 = df_location1.groupby('EmployeeID', as_index=False).sum()
consolidated_data_location2 = df_location2.groupby('EmployeeID', as_index=False).sum()

# Merge the consolidated data for employees working at both locations
consolidated_data_both_locations = pd.merge(consolidated_data_location1, consolidated_data_location2, on='EmployeeID', suffixes=('_loc1', '_loc2'), how='outer')
consolidated_data_both_locations['Data1'] = consolidated_data_both_locations['Data1_loc1'] + consolidated_data_both_locations['Data1_loc2']
consolidated_data_both_locations['Data2'] = consolidated_data_both_locations['Data2_loc1'] + consolidated_data_both_locations['Data2_loc2']
consolidated_data_both_locations['Data3'] = consolidated_data_both_locations['Data3_loc1'] + consolidated_data_both_locations['Data3_loc2']

# Remove the unnecessary columns from the consolidated DataFrame
consolidated_data_both_locations.drop(columns=['Data1_loc1', 'Data1_loc2', 'Data2_loc1', 'Data2_loc2', 'Data3_loc1', 'Data3_loc2'], inplace=True)

# Convert the consolidated data to a list
consolidated_data_list = consolidated_data_both_locations.values.tolist()

# Determine the starting row for placing the consolidated data
start_row = 3  # Assuming you want to start placing the consolidated data in row 2

# Put the consolidated data back into the Excel worksheet
for row_index, row_data in enumerate(consolidated_data_list):
    for col_index, cell_value in enumerate(row_data):
        cell = ws.cell(row=start_row + row_index, column=col_index + 1)
        cell.value = cell_value

# Save the updated workbook
wb.save("StaffPerformanceOverviewtest-06-23 test copy.xlsx")


***

In [14]:
import pandas as pd
from openpyxl import load_workbook

# Load the existing Excel workbook
wb = load_workbook("StaffPerformanceOverviewtest-06-23 test copy.xlsx")

# Select the worksheet you want to update (assuming it's the first sheet)
ws = wb.active

# Read the data from the worksheet into a Pandas DataFrame
data_range = ws['A3:D18']  # Assuming your data is in column A starting from row 2
data = [[cell.value for cell in row] for row in data_range]
df = pd.DataFrame(data, columns=['EmployeeID', 'Data1', 'Data2', 'Data3'])

# Consolidate data based on EmployeeID and sum the values
consolidated_data = df.groupby('EmployeeID', as_index=False).sum()

# Convert the consolidated data back to a list
consolidated_data_list = consolidated_data.values.tolist()

# Put the consolidated data back into the Excel worksheet
for row_index, row_data in enumerate(consolidated_data_list):
    for col_index, cell_value in enumerate(row_data):
        cell = ws.cell(row=row_index + 3, column=col_index + 1)
        cell.value = cell_value

# Save the updated workbook
import pandas as pd
from openpyxl import load_workbook

# Load the existing Excel workbook
wb = load_workbook("StaffPerformanceOverviewtest-06-23 test copy.xlsx")

# Select the worksheet you want to update (assuming it's the first sheet)
ws = wb.active

# Read the data from the worksheet into a Pandas DataFrame
data_range = ws['A3:D18']  # Assuming your data is in column A starting from row 2
data = [[cell.value for cell in row] for row in data_range]
df = pd.DataFrame(data, columns=['EmployeeID', 'Data1', 'Data2', 'Data3'])

# Consolidate data based on EmployeeID and sum the values
consolidated_data = df.groupby('EmployeeID', as_index=False).sum()

# Convert the consolidated data back to a list
consolidated_data_list = consolidated_data.values.tolist()

# Put the consolidated data back into the Excel worksheet
for row_index, row_data in enumerate(consolidated_data_list):
    for col_index, cell_value in enumerate(row_data):
        cell = ws.cell(row=row_index + 3, column=col_index + 1)
        cell.value = cell_value

# Save the updated workbook
wb.save("StaffPerformanceOverviewtest-06-23 test copy.xlsx")



In [2]:
import numpy as np
from openpyxl import load_workbook

# Load the existing Excel workbook
wb = load_workbook("StaffPerformanceOverviewtest-06-23 test copy.xlsx")

# Select the worksheet you want to update (assuming it's the first sheet)
ws = wb.active

# Read the data from the worksheet into a nested list
data_range = ws['A3:D18']  # Assuming your data is in column A starting from row 2
data = [[cell.value if isinstance(cell.value, (int, float)) else 0 for cell in row] for row in data_range]

# Convert the nested list to a NumPy array
data = np.array(data)

print("Data array:")
print(data)

# Check if there are any non-numeric values in the data array
non_numeric_mask = ~np.isreal(data)
if np.any(non_numeric_mask):
    print("Warning: Non-numeric values found in the data array!")
    print("Indices of non-numeric values:")
    print(np.where(non_numeric_mask))

# Calculate the sum using numpy
total_sum = np.sum(data)

# Put the total_sum back into the Excel worksheet
ws['A20'] = total_sum  # Assuming you want to place the total sum in cell A8

# Save the updated workbook
wb.save("StaffPerformanceOverviewtest-06-23 test copy.xlsx")


Data array:
[[ 0 38 20  4]
 [ 0 24  7  3]
 [ 0 25 15  4]
 [ 0 17  6  6]
 [ 0 19 18  1]
 [ 0  8  7  1]
 [ 0  5  5  0]
 [ 0  3  3  1]
 [ 0  1  1  0]
 [ 0 51 22 10]
 [ 0 44 24  6]
 [ 0 34 14  8]
 [ 0 39 19 10]
 [ 0 26 21  5]
 [ 0  8  3  0]
 [ 0  1  0  0]]
